image: alpine

pages:
  script:
  - apk --no-cache add make py3-setuptools python3-dev
  - python3 -m pip install sphinx sphinx_rtd_theme
  - cd manual
  - make html
  - mv build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - master
