image: alpine

before_script:
- apk --no-cache add make py3-setuptools python3-dev
- python3 -m pip install sphinx sphinx_rtd_theme

pages:
  stage: deploy
  script:
  - cd manual
  - make html
  - mv build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - master

test:
  stage: test
  script:
  - cd manual
  - make html
  - mv build/html/ ../test/
  artifacts:
    paths:
    - test
  except:
  - master
