image: openlp/documentation

pages:
  stage: deploy
  script:
  - cd manual
  - make html
  - mv build/html/ ../public/
  - make latex
  - cd build/latex
  - make all-pdf
  - mv OpenLP.pdf ../../../public/
  artifacts:
    paths:
    - public
  only:
  - master

test:
  stage: test
  script:
  - cd manual
  - make html
  - mv build/html/ ../test/
  - make latex
  - cd build/latex
  - make all-pdf
  - mv OpenLP.pdf ../../../test/
  artifacts:
    paths:
    - test
  except:
  - master
